### ISSUE TITLE
leveling and item stats issue

### ISSUE THREAD

**Issue by teoxihuitl** [thetrueoneshots/CubeMegaMod#16]
when im using just the megamod all my items have -2.7million stats for each one like my weapon will have -2.7mil damage or the armor will have -2.7m health. when i combine it with the pyro leveling mod though its the opposite the weapons and armor now have 2.7 million damage and they also take level 2.7m to equip so i cant use any new gear and im invincible for some reason the damage doesnt scale up either it stays at one. i also dont level up at all when using the mods

**Comment by gijsgroenewegen** [comment]
I see you have closed this issue so I assume this has been fixed. Are you willing to share the issue and solution so others can find this more easily?

**Comment by teoxihuitl** [comment]
Use /setcenter then after the center is set use /recenter and it should be normal thats what fixed it for me
