### ISSUE TITLE
[ID:10] All my quests are located in Duralur hills

### ISSUE THREAD

**Issue by mmds1** [thetrueoneshots/CubeMegaMod#17]
All my quests are located in Duralur Hills and they don't gain any progress. What do I do?? My /setcenter location is not ever near this place

**Comment by mmds1** [comment]
I think this is incompatibility with some mod, but I don't know which one

**Comment by gijsgroenewegen** [comment]
The location of quests is indeed an issue that has not been fixed. Quest progression is something that should work regardless of the quest region location. Once I seperated the megamod into seperate mods then I should be able to fix the region issue.

Regarding your issue with quest progression, I am guessing you are either not using the latest version of the megamod (xp compatible release) or not using the latest modloader version (packaged with the latest pyroprogression release). Sorry for the inconvenience of not release this modloader version officially.
