### ISSUE TITLE
Monk can't equip any stuff

### ISSUE THREAD

**Issue by Cirrus-Kun** [thetrueoneshots/CubeMegaMod#18]
Hi, when i played cubemegamod 1.5.7 pyro, my monk can't equip any stuff . It's normal?

**Comment by gijsgroenewegen** [comment]
Yes, this makes sense. This is because of multiple hooks changing the same things. I propose you run with an earlier version of the pyroprogression mod (I think v1.1 should still work with the megamod monk). Thanks for letting me know!

**Comment by Cirrus-Kun** [comment]
Ok, thank you for this advice and nothing, if it helps to improve this mod which is extremely good and which makes the way of playing more pleasant

**Comment by gijsgroenewegen** [comment]
I will look into balancing and bug fixing along the way of development :)
