### ISSUE TITLE
Too many of mobs in the sea

### ISSUE THREAD

**Issue by Cirrus-Kun** [thetrueoneshots/CubeMegaMod#19]
There are too many mobs in the sea so the game bug and crash in multiplayer

**Comment by gijsgroenewegen** [comment]
Yes, the sea exploration mod is very buggy! It is best to disable it when running with the megamod. Future plans include separating the megamod into separate mods, so that you can add to the game whatever you like!

**Comment by Cirrus-Kun** [comment]
Ok, is very good thank you!
