### ISSUE TITLE
Create a mod Voice for our characters

### ISSUE THREAD

**Issue by Cirrus-Kun** [thetrueoneshots/CubeMegaMod#20]
Hello, here I have a request that could be nice to bring to the mod, it would be cool if there was a mod that added voices to our characters and that the voices could be personalized from the game files

**Comment by gijsgroenewegen** [comment]
I think that is a very fun idea. What kind of voices do you have in mind? (Minecraft sounds or voiceovers or something else?)

**Comment by Cirrus-Kun** [comment]
Hey! Thank you for answering me, for the voices the two proposals are good, so there would be a choice for the player CX

**Comment by gijsgroenewegen** [comment]
Would be a fun thing to implement but quite a big thing. Will keep it in mind :D
