### ISSUE TITLE
Gem trader

### ISSUE THREAD

**Issue by Excalibur784** [thetrueoneshots/CubeMegaMod#6]
This is less of a bug but more of a quality of life feature request. You added custom items to the Gem Trader like spirit cubes and artifacts, but the gems were removed. Can you have the Gem trader sell the new items you added plus the gems it used to sell?

**Comment by thetrueoneshots** [comment]
It was a design choice to remove the gems, but I can add them back for you. 👍 It will be there in the release of next week.

**Comment by Excalibur784** [comment]
do you have a discord server? Or is there a common server where you hang out. It would be fun to talk to you.

**Comment by DieuDeGlace** [comment]
id hate to open this back up, but I don't see gems still. Unsure if it was fixed or not, trying to build a version where gem traders aren't touched but normal shop vendors are, but it keeps failing
